name: 'Publisher'
description: 'Publishes events to Lightlytics Producer'
inputs:
  plan-json:
    description: 'Path to Terraform plan file'
    required: true
runs:
  using: 'node12'
  main: 'index.js'